### PR TITLE
Fix artifactory upload

### PR DESCRIPTION
**Pull request by andrewhavck**

### CODE REVIEW

**Review by matt-glover — APPROVED** [review]

**Comment by matt-glover** [comment]
Just to confirm we're targeting master on purpose here for the merge?

**Comment by andrewhavck** [comment]
@matt-glover This is what @grantjoy originally targeted.

**Comment by grantjoy** [comment]
ship it

**Comment by grantjoy** [comment]
Hey @andrewhavck! How's it goin!? Can we close this PR?? 😂 It perpetually shows up in my `Mentioned` inbox.
Screenshot 2024-09-23 at 3 44 45 PM

**Pull request closed without merging**
